EntityState = {
  ASCENDING = 0;
  DESCENDING = 1;
  LANDING = 2;
  GROUNDED = 3;
  RAGDOLL = 4;
}

RenderPass = {
  RENDERPASS_SKYBOX = 0;
  RENDERPASS_TERRAIN = 1;
  RENDERPASS_DYNAMIC = 2;
}

LogLevel = {
  FATAL_ERROR = 0;
  NON_FATAL_ERROR = 1;
  WARNING = 2;
  SUCCESS = 3;
  DEBUG_PRINT = 4;
  INIT_PRINT = 5;
  MASS_DATA_PRINT = 6;
}